export const recipes = [
    {
      "URL": "https://www.smulweb.nl/recepten/1360897/Spaanse-gehaktballetjes-in-tomatensaus-tapas",
      "ingredients": "['Benodigdheden voor de gehaktballetjes:', '500 gram gehaktbr 2 eierenbr beschuit of paneermeelbr 1 grote ui (in kleine stukjes snijden)br 3 tenen knoflookbr nootmuskaatbr paprikapoederbr 1 theelepeltje zoutbr tijmbr br Benodigdheden voor de tomatensaus:br 1 uibr 1/3 blokje vleesbouillon in een koffiekopje met warm water doen.br 2 kleine tomaten (in blokjes snijden)br 1,5 wijnglas rode wijn']",
      "title": "Spaanse gehaktballetjes in tomatensaus (tapas)",
      "description": "Dit recept is door mijn zusje meegenomen nadat zij dit gegeten had bij kennissen in Spanje.Het is echt heerlijk. Wij eten het vaak als hoofdgerecht op een zaterdag. Maar het is eigenlijk een tapas. Heel goed op feestjes of heerlijk op een zonnige zondagmiddag",
      "steps": "Benodigdheden voor de gehaktballetjes door elkaar mengen en er gehaktballetjes van draaien.Olijfolie in de Koekenpan doenDe gehaktballetjes erin doen en bruin bakken op een hoog vuurWanneer dit bijna gaar is, de ui, bouillon en tomaat erbij doen.Daarna anderhalf wijnglas rode wijn erbij doen.Tijm naar smaak toevoegenEn als laatste nog 1 teentje geperste knoflook erbij doen.Dit alles laten pruttelen tot het een sausje wordt.",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/recipe-images/63c16c499aafd-webredactie.jpg.jpg?VersionId=VO..UGf295XjiDkkZ8fj4L67O6a.4ew.&itok=vI1leDW-"
    },
    {
      "URL": "https://www.smulweb.nl/recepten/1153980/De-enige-echte-spaghetti-bolognese-ragu-bolognese",
      "ingredients": "['250 gr rundsgehakt ? 250 gr varkensgehakt ? 100 gr ', 'ontbijtspek', ' of rauwe ', 'ham', ', in stukjes gesneden, 1 ui, 1 teentje ', 'knoflook', ',1 tak selder, 1 wortel, \u00bd liter rode wijn, 100 ml ', 'bouillon', ', 1 blik gepelde tomaten, 2 eetlepels tomatenpuree, ', 'peper', ' en zout, ', 'oregano', ', ', 'basilicum', ', ', 'paprika', ', rozemarijn, tijm, 1 laurierblad., ', 'boter', ', ', 'olijfolie']",
      "title": "De enige echte spaghetti bolognese (Ragu bolognese)",
      "description": "Als je in Itali\u00eb spaghetti bolognese vraagt , zal men je misschien vragend aankijken. Wat wij bolognese noemen, heet in Itali\u00eb gewoon rag\u00f9. Om deze saus der sauzen te maken, moet je wel vroeg uit de veren.Als je dan toch voor dag en dauw opstaat, ga je naar de vroegmarkt en bestelt daar",
      "steps": "Je warmt de boter en olijfolie op en fruit daarin de fijngehakte ui, selder en wortel en het teentje knoflook. Dan bak je het gehakt en spek erin met het laurierblaadje. Roer alles goed dooreen, zodat het vlees niet aanbakt. Als het vlees gebakken is haal je het knoflookteentje eruit en doet er de tomaten, wijn,bouillon, tomatenpuree, peper, zout en veel kruiden bij.Dit laat je dan op een heel zacht vuur enkele uren sudderen. Het mag gerust 3 ? 4 uur blijven staan (Begrijp je nu waarom je zo vroeg op moest?). Het is echt wel belangrijk dat de saus zo lang op het vuur staat, zodat alle vocht verdampt is. Voeg er op het laatst de fijngehakte basilicum bij. Haal de pan van het vuur en doe er eventueel nog wat boter bij.Ondertussen kook je de tagliatelle of spaghetti al dente en je giet de rag\u00f9 over de pasta.",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/recipe-images/63e8965049fe6-spaghetti_bolognese_ragu.jpg.jpg?VersionId=hM3I7._bjedT7iZJb9RZlTHY_N_R6Yal&itok=aX4OHO6C"
    },
    {
      "URL": "https://www.smulweb.nl/recepten/1406384/Lekker-ovenschotel-spitskool-champignons-spekreepjes-en-prei",
      "ingredients": "['Plm. 750 gram ', 'spitskool', '1 preibr 250 gram champignonsbr 150 gram mager gerookte spekreepjes of baconreepjesbr 1 eetlepel neutrale oliebr peper, zoutbr 1/2 theelepel gemalen nootmuskaatbr cayennepeper naar smaakbr 1 + 1 eetlepel mosterdbr 200 ml cr\u00e8me fra\u00eechebr 750 gram kruimige aardappelenbr 50 geraspte belegen kaas']",
      "title": "Lekker! Ovenschotel spitskool champignons spekreepjes en prei",
      "description": "Lekker pittigeovenschotel. Door het gebruik van de mosterd en cr\u00e8me fra\u00eeche krijgt de kool een lekkere romige smaak. Geen aardappelpuree bovenop, maar aardappelen gestampt met wat cr\u00e8me fra\u00eeche en mosterd erdoor geroerd. Hierdoor krijg je een wat grovere laag, die heerlijk is bij de spitskool.Ook lekker met plakjes ontbijtspek op de schotel. Ze worden lekker knapperig in de oven. (zie foto)",
      "steps": "Verwarm de oven voor op 200 graden.Verhit de olie in de wok.Bak hierin de spekreepjes knapperig. Voeg de plakjes champignons toe en bak deze mee tot al het vocht is verdwenen. Voeg de prei toe en bak deze plm. 2 minuten mee. Doe dan de spitskool erbij en roerbak alles nog plm. 5 - 10 minuten, afhankelijk van de dikte van de spitskool. (De spitskool moet nog knapperig blijven!)Maak de spitskool op smaak met peper, zout, nootmuskaat en wat cayennepeper. Roer 2 eetlepels cr\u00e8me fra\u00eeche en 1 eetlepel mosterd door de kool.Doe de kool in een vuurvaste ovenschool.Laat de gare aardappels goed droog stomen.Stamp de aardappels met een stamper grof en roer de rest van de cr\u00e8me fra\u00eeche en 1 eetlepel mosterd door de aardappelen.Strijk de aardappelen uit over de spitkool en bestrooi met wat geraspte kaas.Zet de schaal in de voorverwarmde oven tot de kaas een goudbruine kleur heeft gekregen.Als de ingredi\u00ebnten nog warm zijn kun je de schaal ook even onder de grill zetten tot de kaas goudbruin is.",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/styles/recipe_teaser/public/recipe-images/IMG_1442.JPG_16.jpg?VersionId=r_Ft8svI805cr7fVH1ovjHq6Xlm17Kow&itok=M8vuWts3"
    },
    {
      "URL": "https://www.smulweb.nl/recepten/1064124/Tiramisu",
      "ingredients": "['Geraspte bittere ', 'chocola', ' of cacao, lange vingers, 1 kopje hele sterke ', 'koffie', ', 1 klein scheutje Amaretto, 3 hele verse eieren, 3 eetlepels basterdsuiker, 250 gr. Mascarpone']",
      "title": "Tiramisu",
      "description": "Il vero tiramisu tradizionale, come lo fa la mamma! Hier zit GEEN slagroom in! Je zult in Italie van je lang zal ze leven geen tiramisu vinden met slagroom erin! Hier dus het meest traditionele en ongecompliceerde tiramisu recept. Succes gegarandeerd! Het gaat bij ons in de familie al vele generaties mee, dat zegt al genoeg...",
      "steps": "Neem een schaal en bedek de bodem 1 laag ei/mascarpone mengsel, leg hier een laag lange vingers op die je eerst heel licht in het koffie/amaretto mengsel hebt gedoopt en strooi er vervolgens een laagje gezeefde cacao op. Dit herhalen. De bovenste laag moet ei/mascarpone mengsel met cacao zijn. Het geheel minimaal 4 uur in de koelkast laten staan, maar beter nog is het 1 dag van tevoren klaar te maken.",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/recipe-images/633c285ded1ab-599338_10151071610037766_1626186021_n.jpg.jpg?VersionId=MDo3Rjtd7IjOk7ij14OGHz5O02oJse2.&itok=5vvKmUV_"
    },
    {
      "URL": "https://www.smulweb.nl/recepten/1339716/Zalmwraps-gevuld-met-salade",
      "ingredients": "['2 ', 'wraps', '', '200 gram ', 'gerookte zalm', '', 'klein bakje demi ', 'creme fraiche', '', '3 eetlepels rode ', 'pesto', '', '1 zak ', 'veldsla', '', '1/2 ', 'komkommer', '', 'half bakje cherry tomaatjes en/of zongedroogde ', 'tomaten', ' op ', 'olie', '', 'geroosterde zonnebloempitten en/of ', 'pijnboompitten', '', 'saladedressing naar keuze (ik vind zelf honing mosterd lekker) In elk geval niet te veel/sterk, omdat het niet mag overheersen.']",
      "title": "Zalmwraps gevuld met salade",
      "description": "Dit is echt een goddelijk recept en nog redelijk gezond ook.",
      "steps": "Meng de creme fraiche met de pesto en smeer dit uit over de 2 wraps. Leg hier de plakjes gerookte zalm op. Halveer de wraps.Snijd de komkommer in plakjes en de tomaatjes in kwartjes en meng dit met de sla en de geroosterde pitjes en de dressing. Leg dit op de wraps en vouw ze dicht.",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/recipe-images/6333341d74f75-1352570809.jpg.jpg?VersionId=qOuwiqle.db3uVk3cK7AafW_l.zncSvy&itok=u2BPUZl6"
    },
    {
      "URL": "https://www.smulweb.nl/recepten/1404053/Overheerlijke-anders-dan-anders-italiaanse-ovenschotel",
      "ingredients": "['- 2 mooie, ongepaneerde, varkensschnitzels', '\\n- 1 pakje gezeefde tomaten of 1 blikje tomatenblokjes, net hoe grof/fijn je de saus wilt hebbenbr \\n- 1 grote courgettebr \\n- 1 zak verse spinaziebr \\n- 2 grote of 4 kleine teentjes knoflookbr \\n- 1 grote of 2 kleine sjalotjesbr \\n- 1 bol mozzarellabr \\n- flink wat vers geraspte Parmezaanse kaas of oude Pecorinobr \\n- een handje vol verse basilicumbr \\n- gedroogde Italiaanse kruiden, peper en zout naar smaak (genoeg om het bovenste laagje in je ovenschotel te vormen)']",
      "title": "Overheerlijke, anders dan anders Italiaanse ovenschotel",
      "description": "\u00c9\u00e9n van de lekkerste ovenschotels die ik ken en ook nog eens boordevol groenten en dus vitamines!Ge\u00efnspireerd door Rudolph van Veen, maar met een compleet eigen uitvoering genieten van alle lekkere smaken die Itali\u00eb in zich heeft!",
      "steps": "Fruit in het overgebleven bakvet van de schnitzels (niet weggooien dus, zit veel te veel smaak aan!!) eerst de sjalotjes kort aan en doe daarna de knoflook erbij. Als ze beiden een beetje kleur hebben, doe je er de courgetteblokjes bij. Bak deze even op hoog vuur mee.Als de courgettes een mooi bruin kleurtje hebben, zet dan het vuur op halve hoogte. Doe handje voor handje de spinazie in de pan erbij, zodat het de kans krijgt om te slinken. Als laatste giet je er de gezeefde tomaten/tomatenblokjes bij en laat je alles even goed doorwarmen. Zet het vuur uit en roer er de in stukjes gescheurde basilicumblaadjes doorheen.Leg de plakken mozzarella op de schnitzels in de ovenschotel en giet er daarna de saus overheen.Als laatste bedek je alles met een mooie laag geraspte kaas en zet je de ovenschotel zo`n 10 minuten in de oven.Na 10 minuten kun je er nog voor kiezen om even de grill aan te zetten, zodat je een mooi krokant laagje op je schotel krijgt.Haal eerst de schnitzel met de mozzarella onder de saus vandaan, leg deze op een bord en schep daarna rijkelijk de saus er overheen.Garneer eventueel met nog wat vers geraspte kaas en basilicumblaadjes.",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/styles/recipe_teaser/public/recipe-images/Ovenschotel.jpg.jpg?VersionId=_YGrTUJ03WjSf5svP91FbJKC8nwQYWFs&itok=PJ5TsIRi"
    },
    {
      "URL": "https://www.smulweb.nl/recepten/1128800/Aardappelsalade-a-la-petra",
      "ingredients": "['8 middelgrote ', 'aardappelen', ' - 2 kruidenbouillontabletten - 1 kleine ', 'ui', ' - 1 dl witte ', 'azijn', ' - 1 eetlepel ', 'suiker', ' - ', 'peper', ' en zout - 2 afgestreken eetlepels ', 'mayonaise', ' - 1 eetlepel magere ', 'kwark', ' of ', 'yoghurt', ' - 2 eetlepels fijngehakte ', 'bieslook', ' of ', 'peterselie']",
      "title": "Aardappelsalade a la petra",
      "description": "Aardappelsalade maakte ik altijd volgens het recept van mijn Duitse moeder. Maar door tijdgebrek ontstond dit recept. Nu is mijn aardappelsalade nog veel lekkerder, hoeft niet meer in te trekken en dus veel sneller klaar. Iedereen die de salade geproefd heeft wil het recept. De salade kun je ook als basis gebruiken voor een maaltijdsalade door er gebakken spekreepjes of hamreepjes of tonijn of gerookte zalm aan toe te voegen. Laat je eigen fantasie maar werken. De salade is verrukkelijk dat kan ik je verzekeren!",
      "steps": "Aardappelen schillen en in niet al te dikke schijfjes snijden.Aardappelschijfjes opzetten met kruidenbouillontabletten en zoveel water dat de plakjes net onder staan. Aardappelschijfjes aan de kook brengen en plm. 3 minuten koken. Als de aardappelen zo goed als gaar zijn azijn, suiker en gesnipperde ui toevoegen. Weer aan de kook brengen en nog plm. 3 minuten koken. In het vocht 10 minuten laten afkoelen. Afgieten in een vergiet en de aardappelschijfjes goed laten uitlekken. Yogurt of kwark mengen met de mayonaise en de gehakte kruiden. Af laten koelen en smullen maar!",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/recipe-images/632749d8b5523-1128800.jpg.jpg?VersionId=oxipxDw4zQnCQl7bzOvngv.STL7dLybe&itok=WWA8qeuw"
    },
    {
      "URL": "https://www.smulweb.nl/recepten/446082/Muchos-nachos",
      "ingredients": "['-grote zak nacho ', 'chips', ', ', 'chili', ' of cheese flavoured.', '', '-200 gr ', 'gehakt', '.', '', '-200 gr ', 'kipfilet', '', '-cheddar of andere pittige smeltkaas', '', '-quacemole(recept komt)', '', '-salsa, uit een potje of zelf gefabriceerd', '', '-', 'chilipoeder', '', '-tomatenpuree en ', 'ketchup', '', '-tabasco', '', '-', 'peper', ' en zout', '', '- mexicaanse ', 'kruiden', ' voor vlees', '', '-flesje ', 'rode wijn', '', '-', 'paprika', ' of mexicaanse mix van groenten', '', '-eigen inbreng is hier zeer welkom!', '', ' gooi erbij wat je lekker lijkt.', '', '-een lekker biertje voor tijdens de voorbereiding.']",
      "title": "Muchos Nachos!",
      "description": "Vaak gegeten in Mexicaans restaurant, smaakte zo goed dat ik het ook zelf heb geprobeerd, en het was erug lekker!",
      "steps": "Het gehaktbegin met het gehakt los te bakken, met zout, peper en wat mexicaanse kruiden, voeg extra chilipoeder toe en wat tabasco.Een blikje tomatenpuree of een flinke klodder tomatenketchup en een flinke scheut wijn.Laat op een laag pitje lekker sudderen terwijl je de rest klaar maakt.de kipSnij de kip in erg kleine stukjes en bak wederom met zout, peper, chilipoeder, paprikapoeder en mexicaanse kruiden op hoog vuur in een braadpannetje totdat ze gaar en lekker bruin is, voeg ook hierbij een klodder tomatenketchup enwat je verder nog nodig vind.Verdeel de paprika of de groenten tussen de twee pannetjes en bak zeer kort even mee, de groente blijft lekker knapperig.Ondertussen heb je de grill natuurlijk al voorverwarmd en in een Ovenschaal een dikke bodem van tortillachips (eventueel kun je er een maistortilla onder leggen) alvast even voorverwarmd in de oven,leg aan de ene kant het gehakt, aan de andere kant de kip op de nachos en bestrooi het hele zaakje royaal met gerapste kaas.Even onder de grill tot alles lekker gesmolten is.EEn lekkere dikke klodder quacomole en desnoods creme fraiche erbij,en klaar is je muchos nachos!",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/recipe-images/632748ae52b86-529174_10151040592902766_187794573_n.jpg.jpg?VersionId=g.RFaYSfNAKAV8LmhLN7Om615113LOL4&itok=XHbvjQvL"
    },
    {
      "URL": "https://www.smulweb.nl/recepten/1110310/Prei-aardappel-gehakt-ovenschotel",
      "ingredients": "['700 gr aardappels300 gr ', 'gehakt', '  6 preien gesneden  3 eieren  ? bekertje ', 'creme fraiche', '  100 gr verse geraspte Parmezaanse ', 'kaas', '  30 gr ', 'boter', '  beetje ', 'olijfolie', ' ', 'peper', ' en zout 2 tl ', 'tijm', '.  ', 'melk', ' (', 'aardappelpuree', ')']",
      "title": "Prei - aardappel, gehakt ovenschotel",
      "description": "Heerlijke en toch makkelijke ovenschotel. Met verse Parmezaansekaas, creme fraiche, eieren en kruiden!!",
      "steps": "Maak de aardappelpuree volgens eigen idee. In pan olie en margarine verwarmen en de prei toevoegen. Bak de prei in ca 5 minuten en steeds even omscheppen, voeg nu het gehakt toe en bak tot het gerulde gehakt gaar is. Klop de eieren samen met de creme fraiche en de helft van de Parmezaanse kaas, zout en peper. Voeg bij de prei wat zout en tijm toe. Na ca 15 minuten het eiermengsel door de prei scheppen. Doe onderin de Ovenschaal de aardappelpuree en schep het preimengsel hier op. Strooi nu de Parmezaanse kaas over de ovenschotel en zet deze voor ca. 15-20 minuten in de voorverwarmde oven",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/recipe-images/632749c364dae-webredactie.jpg.jpg?VersionId=Mzj9W5U.OUJtmqcfl_qzHy.J.NfiGIkt&itok=ZeUjw-yn"
    },
    {
      "URL": "https://www.smulweb.nl/recepten/1140181/Turkse-tortilla-met-yoghurtsaus",
      "ingredients": "['1 sjalot, fijngesnipperd', '', '1 rode (punt)paprika, in kleine blokjes', '', '1-2 teentjes ', 'knoflook', ', fijngesneden of uit de pers', '', '150 g rundergehakt (of ', 'lamsgehakt', ' als je dat kunt krijgen)', '', '1 el ', 'olijfolie', '', 'zout en (versgemalen) peper', '', '4 (', 'bloem', ') tortillas', '', 'snuf ', 'nootmuskaat', '', '2 tl komijn', '', '2 tl kaneelpoeder', '', '2 tl cayennepeper', '', '1 el paprikapoeder', '', 'Eventueel: peterselie, fijngesneden', '', '1/4 krop ', 'ijsbergsla', ' of witte ', 'kool', ', in reepjes gesneden', '', 'Voor de pizzasaus:', '', '1 blikje tomatenpuree', '', 'paprikapoeder', '', '3 el ', 'bouillon', '', '1 el olijfolie', '', 'Voor de yoghurtsaus:', '', '1,5 dl Bulgaarse yoghurt', '', 'witte peper, zout', '', '1-2 teentjes knoflook', '', 'ca. 6 blaadjes ', 'munt', ' (kan ook weggelaten worden, vervang eventueel door ', 'koriander', ' of peterselie)', '', 'Eventueel extra:', '', 'Sweet chillisauce']",
      "title": "Turkse tortilla met yoghurtsaus",
      "description": "Snelle en superlekkere variant op Sis kofte. Gezond junkfood bestaat!",
      "steps": "Oven voorverwarmen op 200C en rooster bekleden met aluminiumfolie.Bestrijk de tortillas met de pizzasaus. Laat de randen vrij en besproei deze met water (om te voorkomen dat ze te knapperig worden en je ze niet meer makkelijk kunt oprollen).Olijfolie in een pan op hoog vuur verhitten. Het gehaktmengsel kort rul bakken en verdelen over de tortillas. Bak ze ca. 2-3 minuten in de oven. Verdeel ijsbergsla of witte koolreepjes over het midden en rol de pizzas op. Serveer met de yoghurtsaus en eventueel sweet chillisauce.",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/recipe-images/63274a179ec44-webredactie.jpg.jpg?VersionId=AmF6mEKeuy.w7fNramLVQwwPYOvRWn7v&itok=LCYxSzIJ"
    },
    {
      "URL": "https://www.smulweb.nl/recepten/1366288/Vlaams-stoofvlees",
      "ingredients": "['2 ', 'uien', '1 teen knoflookbr ']",
      "title": "Vlaams stoofvlees",
      "description": "Antwerpen is een Bourgondisch paradijs.In de stad zijn veel verschillende keukens terug te vinden waar je heerlijkkunt eten.Maar naast de vele restaurants zijn er natuurlijk ook de befaamdefrietkotten.Vooral in combinatie met Vlaams stoofvlees zijn de Belgische frietenverrukkelijk.",
      "steps": "Bestrooi het vlees met een beetje bloem.Verhit de boter in een pan en bak het vlees aan.Voeg de uien en knoflook toe en bak ca. 2 minuten.Voeg laurier, tijm, bouillonblokje, kruidnagels en nootmuskaat toe en blushet af met bier.Laat het gerecht ca 2 \u00bd uur zachtjes stoven in de oven op 160 graden.Snijd de aardappelen tot mooie dikke frieten en bak deze ca. 5 minuten voorop 160 gradenen bak ze als het vlees gaar is af op 180 graden tot ze goudbruin zijn.",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/recipe-images/63274c2a98b7c-11-1-1.jpg.jpg?VersionId=4pl8Ycft.In81nyr1GbvZ8vvtnzIWk1Q&itok=6rNzHuKH"
    },
    {
      "URL": "https://www.smulweb.nl/recepten/1363612/Heerlijke-canneloni-met-ricotta-en-spinazie",
      "ingredients": "['25 gr ', 'boter', '25 gr bloembr 350 ml melkbr 12 lasagnebladenbr snufje nootmuskaatbr 1 el olijfoliebr 1 ui, gehaktbr 3 teentjes knoflookbr 1 zal losse spinazieblaadjes (bonduel) of br wat ik doe: LEKKER ZELF EVEN MAKEN.br 8 zongedroogde tomaatjes op olie, in stukjesbr 100 gr zwarte olijven, zonde  pit in stukjesbr 250 gr ricottabr 3 el basilicumbr 150 gr geraspte kaasbr peper en zout']",
      "title": "Heerlijke Canneloni met ricotta en spinazie",
      "description": "Heerlijk met verse basilicum, gehakt, zongedroogde tomaatjes,kaasen olijven.Heerlijk om het is eens uit te proberen.",
      "steps": "Smelt de boter en roer de bloem erdoor. Laat 1 minuut garen en voeg de helft melk toe.Roer de saus, schenk de rest melk erbij. Voeg nootmuskaat, peper en zout toe. Kook lasagnevellen 8 minuten. Laat uitlekken/ Bak knoflook en ui 3 minuten. Roerbak spinazie, schep tomaat en olijven erdoor en haal pan van het vuur. Voeg ricotta, basilicum, peper en zout toe. Leg op elk lasagnevel een lepel vulling en rol op. Leg canneloni in schaal en schenk saus erover,. Strooi kaas erover en zet 15-20 minuten in oven op 180 graden tot de kaas gesmolten is.",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/recipe-images/63b161adeadfc-1_canalonie.jpg.jpg?VersionId=IVw_S9wsEaWR1IG8pLmkwyujQdTmJ.pz&itok=ESOCk-Ke"
    },
    {
      "URL": "https://www.smulweb.nl/recepten/593072/Pilaf-met-perziken",
      "ingredients": "['500 g ', 'kipfilet', ', of kalkoenfilets', '', '1 blik perzikken,', '', '1 blik gepelde ', 'tomaten', ',', '', '1 groot blik ', 'tomatenpuree', ',', '', '1 kippebouillontablet,', '', '5 eetl ketjap Manis,', '', '3 tl ', 'sambal', ' Badjak,', '', 'klein beetje worcestersaus,', '', '1 ui,', '', '2 tenen ', 'knoflook', ',', '', 'beetje ', 'maizena', ',', '', '1 bakje ', 'champignons', ',', '', '1 rode ', 'paprika', ' in blokjes gesneden', '', 'boter', ',', '', 'rijst', ',']",
      "title": "Pilaf met Perziken.",
      "description": "Ik heb dit recept al heel lang en al aan veel mensen gegeven die het ook zo lekker vonden, heb er al meerdere prijzen mee gewonnen.",
      "steps": "Bak de kip even aan, en doe de ui, champignons, knoflook en rode paprikablokjes erbij en ook de ketjap, en sambal, laat dit even lekker bakken.Doe dan de tomatenpuree en de met de staafmixer fijngehakte tomaten erbij, en roer even door. Dan evenveel sap van de perzikken, als water erbij en de perzikblokjes, en de bouillontablet, en laat dit alles even zachtjes sudderen met ook de worcestersaus.Bind de saus met maizena,en breng eventueel op smaak met wat gemalen peper.",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/recipe-images/632748bcdb8ab-IMG_0622.JPG.jpg?VersionId=cWyAl7ioMBuIXbEqdmR5YNRoc80mjun.&itok=2FH5-Hzv"
    },
    {
      "URL": "https://www.smulweb.nl/recepten/1402098/Romige-ovenschotel-witlof-met-champignons-ham-en-kaas",
      "ingredients": "['6 struikjes ', 'witlof', ', schoongemaakt, uiteinde verwijderd', '', 'zout, ', 'peper', '', '250 gram ', 'champignons', ', schoongemaakt in plakjes gesneden', '', '1 middelgrote ', 'ui', ', gepeld en gesnpperd', '', '2 eetlepels ', 'zonnebloemolie', '', '50 + 50 gram belegen ', 'geraspte kaas', '', '200 gram gekookte achterham in kleine reepjes', '', '2 eidooiers', '', '50 ml ', 'slagroom', ' of ', 'melk', '', '800 gram kruimige ', 'aardappelen', '', '1 pakje ', 'boursin', ' (150 gram)']",
      "title": "Romige ovenschotel witlof met champignons, ham en kaas",
      "description": "Weer eens een andere variatie op de gewone \"witlof met ham en kaas\"uit de oven.Bijzonder door de romige champignonmassa en de door de aardappelen gestampte boursin .",
      "steps": "Kook de aardappelen gaar in water met zout. Laat de gare aardappelen goed droogstomen.Stamp de aardappelen fijn met een aardappelstamper en maak hiervan samen met de eiooiers, melk en boursin een lekkere romige aardappelpuree.Kook de struikjes witlof beetgaar. Laat ze heel goed uitlekken in een vergiet. Knijp de struikjes eventueel nog een beetje uit. Leg de struikjes witlof in de ovenschaal.Verhit de olie in de koekenpan. Bak hierin de champignons en de uisnippers lichtbruin. Doe de warmtebon uit.Voeg de hamreepjes en 50 gram geraspte kaas toe en roer alles goed door elkaar.Oven voorverwarmen op 200 graden.Champignon-ham-kaasmassa over de witlofstruikjes verdelen.Aardappelpuree met boursin hierover uitstrijken.Bestrooien met de rest van de kaas.In het midden van de oven van de op 200 graden voorverwarmde oven plm. 30 minuten bakken tot de ovenschotel goudbruin is.",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/styles/recipe_teaser/public/recipe-images/witlof_ovenschotel1.jpg_13.jpg?VersionId=p0zZBiSRK_4ebLTQ3FMFT1H4BOd.8JKa&itok=vD_0MMlC"
    },
    {
      "URL": "https://www.smulweb.nl/recepten/1407122/Stevige-herfst-ovenschotel-met-rundergehakt-heerlijk",
      "ingredients": "['750 gr mager ', 'rundergehakt', '', '4 ons uien (in halve ringen)', '', '3 teentjes ', 'knoflook', ' (fijn)', '', '2 grote winterpenen (julienne)', '', '2 ons fijne ', 'erwten', ' (diepvries)', '', '125 gr ', 'champignons', ' (in halve plakjes)', '', '2 el ', 'tomatenpuree', '', '\u00bd el ', 'tijm', '', '\u00bd liter ', 'kippenbouillon', ' (sterk geconcentreerd)', '', '2 el ', 'bloem', '', '75 ml worchestersaus', '', 'Olijfolie', '', '1 kilo kruimige aardappels', '', '2 eierdooiers', '', '75 gr oude ', 'geraspte kaas', ' of lekkerder, parmezaan', '', 'Zeezout', '', 'Zwarte ', 'peper']",
      "title": "Stevige herfst ovenschotel met rundergehakt, heerlijk!",
      "description": "Het principe lijkt op een Britse sheperd`s Pie, maar is het niet. Zo`n schotel is met ander vlees en is anders gemaakt. Deze heb ik gemaakt naar een oud idee van Gordon Ramsey en heb er, in de loop der jaren, mijn eigen draai aan gegeven. Het idee van Ramsey was om kippenbouillon te gebruiken en het vocht te binden. Heel goed want is echt een smaaksensatie. Is hij lekker, ja, vult hij, ja, is het stevig deze maaltijd, ja, dus een primaovenschotelom de gure donkere maand `November` en de winter mee door te komen. Probeer hem zelf maar en dan hoor ik het wel. Met kook en baktijd meegenomen kan deze in een uurtje dampend op tafel staan. Eet smakelijk !",
      "steps": "Doe een paar scheutjes olijfolie in de Braadpan. Doe het gehakt er in en rul het even totdat het gaat verkleuren. Breng op smaak met zout en peper. Doe nu de gesneden groente er bij, de champignons, de tijm, de knoflook en de tomatenpuree. Lekker zacht laten worden. Doe de kippenbouillon erbij en de bloem en laat eventjes, al roerend pruttelen totdat het hele mengsel mooi dik en stijf is. Breng verder op smaak met de worchstersaus. Kook tegelijkertijd de aardappelen in zout water. Giet ze af als ze gaar zijn, stamp ze dan fijn, doe de eierdooiers erbij en de helft van de kaas. Nu heb je dikke puree die op smaak is gebracht. Als het gehaktmengsel met de groenten ingedikt is doe het dan in een grote ovenschaal. Dek het af met de net gemaakte puree. Gebruik de rest van de kaas om het dak van de schotel mee te bestrooien. Zo krijg je een heerlijke, smakelijke, krokante korst. Zet hem in de voorverwarmde oven en laat hem in 20-25 minuten goudbruin bakken. Dit is echt vreselijk lekker, gezond en voedzaam, dus smullen maar !Kooktip:Om er een leuke draai aan te geven laat dan eens de erwten en de wortel weg en voeg 500 gram zuurkool toe. Ook erg lekker voor de mensen onder ons die van zuurkool houden, nu heb je er twee in \u00e9\u00e9n recept.",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/styles/recipe_teaser/public/recipe-images/herfst_schotel.jpg_10.jpg?VersionId=EwUuhYYBQ5z_0gsGu4QkRxk9o6vknA_M&itok=mqO6DrZu"
    },
    {
      "URL": "https://www.smulweb.nl/recepten/1369929/Spaghetti-carbonara",
      "ingredients": "['400 gr verse ', 'spaghetti', '', '\\n2 eieren', '', '\\n2 eidooiers', '', '\\n60 gr (vers) geraspte Parmezaanse ', 'kaas', '', '\\n2 eetl ', 'olijfolie', '', '\\n30 gr ', 'boter', '', '\\n2 teentjes ', 'knoflook', '', '\\n200 gr ', 'pancetta', '', '\\n', 'peper', ' & zout']",
      "title": "Spaghetti Carbonara",
      "description": "Spaghetti met de originele carbonara saus, zoals de Italiaan deze op tafel zet.",
      "steps": "Kook de spaghetti al dente in een pan met ruim kokend water en een snufje zout.Kluts ondertussen in een kom de eieren met de eidooiers en de parmezaanse kaas.Breng dit mengsel op smaak met wat peper en zout.Snijd de pancetta in dunne reepjes.Verhit de olijfolie met de boter in een pan.Kneus de knoflookteentje met de bolle kant van een lepel en doe ze samen met de pancettareepjes in de pan.Bak tot de pancetta krokant is. Verwijder vervolgens de knoflook.Voeg de uitgelekte spaghetti toe aan de pancettareepjes.Roer alles goed door en haal de pan dan van het vuur.Roer het eimengsel er door en serveer meteen.",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/recipe-images/63274c6df1ba9-carbonara_italiaans.jpg.jpg?VersionId=chY381dVf4eG5IsaXtAP5T0qTEpb.G1k&itok=_iWLoLq2"
    },
    {
      "URL": "https://www.smulweb.nl/recepten/1151725/Romige-kipgratin-afgedekt-met-stokbroodkruidenboter-en-kaas",
      "ingredients": "['250 gram ', 'kipfilet', '  100 gr ', 'kruidenboter', '  150 gram ontbijtspekreepjes600 gr gesneden ', 'prei', '  zout en ', 'peper', '   4 el gesneden ', 'peterselie', '  ca 16 sneetjes ', 'stokbrood', '  200 gr geraspte belegen ', 'kaas', ' VOOR EEN WITTE SAUS25 gram ', 'boter', '', '20 gram ', 'bloem', '', '2 dl heldere  vleesbouillon (van blokje bijvoorbeleld)', '', 'peper', '', 'zout']",
      "title": "Romige kipgratin afgedekt met stokbrood,kruidenboter en kaas",
      "description": "Een waanzinnige ovenschotel, met kip, prei en een dakje van gesneden stokbrood met kruidenboter enkaas. Echt een TOPPERTJE",
      "steps": "Snijd de kipfilet in stukjes.. Verhit 20 gram kruidenboter in een Koekenpan met antiaanbaklaag en roerbak de spekjes en de kipfilet ca 3 minuten. Schep de kip en de spekjes met een schuimspaan in een ovenschaal.  Roerbak in het achtergebleven vet de prei ca 2 minuten. Schep de prei door het kip-preimengsel in de oenschaal. Voeg naar smaak zout en peper toe.  Maak de saus: Smelt de boter in een kleine sauspan en roer er de bloem door tot het een glad geheel is, zonder te kleuren.Roer er geleidelijk de warme bouillon bij, telkens een scheutje als het vorige scheutje is opgenomen.Breng op smaak met zout en peper en laat het nog 5 minuten sudderen. Roer de peterselie er door en schenk de saus over het kipmengsel.  Besmeer de sneetjes stokbrood aan 1 kant met de rest van de kruidenboter en dek hiermee de ovenschotel af. Strooi de kaas over het brood.Zet de ovenschaal in het midden van de oven en laat het gerecht 20 minuten goudbruin en door en door heet worden.",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/recipe-images/63274a7a22172-romige_kipgratin_afgedekt_met_stokbrood_kruidenboter_en_kaas.jpg.jpg?VersionId=ZiYv4073gQtAP2Z9grjrNRrdUVo0OKxs&itok=suwkM_A3"
    },
    {
      "URL": "https://www.smulweb.nl/recepten/1150456/Courgettesoep-op-de-wijze-van-oma",
      "ingredients": "['2 grote courgettes (+- 30cm) ', '', '2 ', 'uien', '', '2 knoflookteentjes', '', '1 eetlepel mosterd', '', '1 koffielepel kerriepoeder', '', '1 koffielepel ', 'paprikapoeder', '', '1,5 l kippebouillon = 2,5 blokjes', '', '1 eetlepel ', 'olie']",
      "title": "Courgettesoep op de wijze van oma",
      "description": "Courgettesoep met kerrie, paprika en mosterd",
      "steps": "Snij de courgettes in blokjes, de uien in reepjes en pers de knoflookteentjes uit. Stoof deze groenten aan in olie.Voeg mosterd, kerrie en paprikapoeder toe en laat eventjes bakken.Giet de kippebouillon erbij. Kook de groenten gaar in +- 20 min.Mix de soep met in staafmixer.Serveer de soep warm.Heel lekker is het om er gruy\u00e8rekaas aan toe te voegen en eventueel brootcro\u00fbtons bij te voegen.Smakelijk",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/recipe-images/63274a75154cf-courgettesoep600_3032.jpg.jpg?VersionId=NJBu92pElwFYnLCTnLvvszKG4vPss0sE&itok=xPVGu2a4"
    },
    {
      "URL": "https://www.smulweb.nl/recepten/1363234/Supermalse-gemarineerde-kipfilet-met-pesto-uit-de-oven",
      "ingredients": "['Per persoon 1 ', 'kipfilet', ' van ongeveer 150 gram.', '', '\\n2 teentjes ', 'knoflook', '', '\\nPotje ', 'groene pesto', '', '\\nPaar zongedroogde tomaatjes op ', 'olie', '', '\\nCitroensap', '', '\\nWat pijnboompitjes', '', '\\nFlinke snuif gedroogde ', 'oregano', '', '\\nEetlepel Franse mosterd', '']",
      "title": "Supermalse gemarineerde kipfilet met pesto uit de oven",
      "description": "De combinatie van marineren en zacht laten garen in de oven maakt deze pittig Italiaans smakende kipfilet heel zacht en mals, je mes zakt er als het ware vanzelf doorheen.",
      "steps": "Dep de filetjes wat droog met een stukje keukenpapier,  smeer ze royaal in met de pesto en leg ze in een ovenschaal.Per filet 2 zongedroogde tomaatjes  erop leggen en strooi er  wat pijnboompitjes over.Laat de kipfilet in 25 minuten in een vooverwarmde oven van circa 185 graden gaar worden.",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/recipe-images/63274bfc8bca4-kippesto4.jpg.jpg?VersionId=U_hWW1JRxgS7SLRIRYhiCYasW7Z49ICT&itok=YuwU9WB_"
    },
    {
      "URL": "https://www.smulweb.nl/recepten/1094638/Een-zalige-en-gezellige-romige-vispotje",
      "ingredients": "['400 g kabeljauwfilet in mooie reepjes, ,', '\\n200 g sjalotjes,  200 g kleine champignons, ,br \\n60 g boter of margarine, ,1 tl suiker, ,br \\nzout en peper, ,30 g bloem, ,br \\n5 dl visbouillon (van tablet), ,br \\n1,25 dl creme fraiche, , 2-3 tl citroensap,,,br br \\n2 vleestomaten, ontveld, in kleine blokjes, ,br \\n2 el grof gesneden dille.br ']",
      "title": "Een zalige en gezellige ROMIGE VISPOTJE",
      "description": "Een stoofpotje van kabeljauw, sjalotjes, champignons,tomaten,  room en kruiden",
      "steps": "Uitjes en champignons in koekenpan  doen, 20 g boter en zoveel watertoevoegen tot beide groenten onderstaan. Suiker, zout en peper toevoegenen op zacht vuur koken tot water verdampt is. Groenten apart zetten. 40 gboter smelten, bloem erdoor roeren en 2 minuten laten bakken. Bouillon encreme fraiche toevoegen en tot gladde saus roeren. Saus op zacht vuur 10minuten laten koken. Saus met zout, peper en citroensap op smaak brengen. Kabeljauw in saus leggen en op zacht vuur laten meestoven tot vis gaar is.Tomaten, uitjes en champignons toevoegen en 2 minuten mee verwarmen.Voor serveren dille erover strooien",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/recipe-images/6391f5e52edd6-1383152109.jpg.jpg?VersionId=bcuD4yDVh.14UYoHb8MTq771fhN8qstt&itok=0_mcrPwh"
    },
    {
      "URL": "https://www.smulweb.nl/recepten/1356876/Amusechampignons",
      "ingredients": "['8 niet al te grote ', 'champignons', '', '75 gram ', 'boursin', ' of andere ', 'roomkaas', ' met ', 'kruiden', '', '100 gram gekookte ', 'ham', ' in hele kleine stukjes', '', 'fijngehakte ', 'peterselie', '', 'wat blaadjes peterselie om te garneren', '', 'geraspte belegen ', 'kaas', '', 'bouillon', ' van tablet']",
      "title": "Amusechampignons",
      "description": "Samen met mijn nichtje van 10 jaar gemaakt die graag een amuse wilde maken.Eenvoudig maar heel lekker. Gevulde champignons geserveerd op een lepel. Hier maak je indruk mee. Heerlijk hapje helemaal vooraf bij een dinertje.",
      "steps": "Vul de champignons met de ham-massa. Zet de champignons in een Ovenschaal. Giet een laagje bouillon in de ovenschaal anders worden de champignons erg droog. Bestrooi de champignons met de geraspte kaas. Zet ze in het midden van de voorverwarmde oven en laat ze plm. 20 minuten bakken tot ze goudbruin zien. Garneer de champignons met een blaadje peterselie.",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/recipe-images/63274b94d9332-1_amusechampignons.jpg.jpg?VersionId=FctLHkMLEETATyr24Yzp_nUk5dPeQYLe&itok=LWWjgEyG"
    },
    {
      "URL": "https://www.smulweb.nl/recepten/1321397/Variaties-met-bladerdeeg-hapjes-voor-de-borrel",
      "ingredients": "['Hoeveelheden zijn moeilijk te geven omdat het afhankelijk is van het aantal ', 'hapjes', ' wat je wilt maken.', '\\nPlakjes (roomboter) bladerdeegbr \\nachterhambr \\njong belegen kaasbr \\nplakjes gerookte zalmbr \\nboursin met kruiden en knoflook (of ander merk)br \\nrundersaucijsjesbr \\nlos geklopte eidooier']",
      "title": "Variaties met bladerdeeg - hapjes voor de borrel",
      "description": "Verrukkelijke kleine gevarieerde bladerdeeghapjes. Ze vlogen weg op Sinterklaasavond. Maar ook bij andere gelegenheden natuurlijk heerlijk. Je kunt ze natuurlijk tevoren maken en invriezen.Ik heb kleine rundersaucijzenbroodjes gemaakt, bladerdeeghapjes met ham en kaas en hapjes met gerookte zalm en boursin. Van de saucijzenbroodjes haal je er 3 uit een plakje bladerdeeg. Van de andere hapjes elk 4.",
      "steps": "Plakjes bladerdeeg ontdooien.Voor de saucijzenbroodjes:Op elk plakje bladerdeeg 1/3 deel van een saucijs leggen. Bladerdeeg oprollen en in 3 stukken verdelen. Bestrijken met eidooier.Voor de ham-kaas-hapjes:Bladerdeeg in vieren snijden. Blokje kaas in stukje ham verpakken. Midden op stukje bladerdeeg leggen. Punten naar elkaar vouwen.Bestrijken met eidooier.Voor de zalm-boursinhapjes:Bladerdeeg in vieren snijden. Bolletje boursin in stukje zalm rollen. Midden op stukje bladerdeeg leggen en als driehoekje naar elkaar vouwen. Bestrijken met eidooier.Oven voorverwarmen op 200 graden C.In het midden van de voorverwarmde oven 15-20 minuten bakken.tot de hapjes mooi goudbruin zijn.",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/recipe-images/63274b56ef93b-bladerdeeghapjesdiv.jpg.jpg?VersionId=CtGewM1IpmjzD.RTXIcmTNykIbdwXWG6&itok=Sl1P71rA"
    },
    {
      "URL": "https://www.smulweb.nl/recepten/1386168/Pikante-goulashsoep-maaltijdsoep-ook-voor-de-slowcooker",
      "ingredients": "['2 flinke uien -', '3 teentjes knoflook -br ']",
      "title": "Pikante goulashsoep maaltijdsoep ook voor de slowcooker",
      "description": "Het recept van deze echt verrukkelijke goulashsoep vond ik achter op een krantje van een supermarkt hier in Duitsland. Het leek me een heerlijke soep voor Nieuwjaarsdag en dat was het ook. We hebben er van genoten! Echt een TOPPER!Toevallig gisteren (7-11-2012) deze heerlijke goulashsoep voor onze buren gekookt. Mijn buurvrouw en ook haar dochter wilden allebei het recept. Ze vonden de soep heerlijk!Naar aanleiding van een vraag van een Smulweb-lid:Als je de soep in deSlowcookerwilt bereiden kun je alle ingredi\u00ebnten er tegelijk in doen. Je hoeft het vlees niet aan te bakken, hoewel ik zelf vind dat er dan een iets vollere smaak aan de soep komt.Ik zet de soep plm. 6 uur op low en vind hem dan erg lekker.",
      "steps": "Pel en snipper de uien en de knoflook.Schil de winterpenen en de aardappelen en snij ze in kleine blokjes.Snij de gepelde tomaten in stukjes, verwijder eventuele velletjes en kroontjes. (Vocht niet weggooien!)Laat de geroosterde paprika`s uitlekken. Verwijder de pitjes en zwarte stukjes. Snij de paprika`s in stukjes of reepjes.Verhit de olie en bak hierin het vlees op hoog vuur rondom bruin.Voeg de ui- en knoflook-snippers toe en bak even mee.Voeg aardappelen, winterpeen en tomatenpuree toe en roer goed door.Voeg de gepelde tomaten, het tomatenvocht en de geroosterde paprika`s toe.Doe er plm. \u00be liter water en de bouillontabletten bij.Roer alles goed door en breng aan de kook.Laat de soep plm. 1 \u00bd - 2 uur zachtjes koken tot het vlees gaar is.Breng de soep op smaak met zout, peper, paprikapoeder en cayennepeper.Ik zet de soep plm. 6 uur op low en vind hem dan erg lekker.",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/recipe-images/63274cf18af25-goulashsoep.JPG.jpg?VersionId=u1ruJXjxcSWKHLjdMki4bDgZlcRmMLf7&itok=2OfnRGkR"
    },
    {
      "URL": "https://www.smulweb.nl/recepten/1400235/De-makkelijkste-stroopwafeltaart-die-er-bestaat-ben-de-le",
      "ingredients": "['2 pakken ', 'stroopwafels', ' (12)', '', '\\n1 zakje mini stroopwafeltjes', '', '\\n600 gram ', 'monchou', ' of zachte ', 'roomkaas', ' (kan ook iets meer)', '', '\\n40 gram basterdsuiker (hoeveelheid ligt aan de mate van zoetekauw zijn;)', '', '\\n150 gram nougatinestukjes', '', '\\n2 zakjes vanillesuiker', '', '\\n1 vanillestokje', '', '\\n500-ml ', 'slagroom', '', '\\n2 zakjes klopfix']",
      "title": "De makkelijkste Stroopwafeltaart die er bestaat (en de le",
      "description": "Echt deze stroopwafeltaart heb ik in een handomdraai bedacht en kan werkelijk iedereen maken. Zelfs de non kokers onder ons.",
      "steps": "Neem de stroopwafels (alle grote) en maal deze in de keukenmachine. Mogen best wat grove stukken inzitten (dat is juist lekker!).Klop ondertussen de slagroom en klopfix stijf en voeg hier de roomkaas, vanillesuiker, suiker en het merg van een vanillestokje bij. Dan als laatste de nougatine. Proef tussendoor goed of het niet te zoet wordt. Laat dan gewoon de suiker achterwege (vind ik persoonlijk lekkerder).Neem de grof gemalen koekkruimels en verwarm deze even kort in de magnetron of pannetje (zodat de stroop lekker kleverig wordt).Bedek een ingevette springvorm met een deel van de koekkruimels (en wat gebroken wafels zodat er nog flinke stukken tussen zitten)als bodem en druk goed aan.Doe hier nu een flinke laag roomkaas-slagroom mengsel op en hierover strooi je wat stroopwafel brokjes/stukken. Vervolgens weer een flinke laag roomkaas-slagroom en maak het geheel af met de overige stroopwafelbrokjes.Dan als finishing touch de mini stroopwafeltjes over de taart decoreren (en 3 uur opstijven in de koelkast) en klaar is kitt.In een half uurtje een prachtige taart die echt om te smullen zo lekker is.",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/styles/recipe_teaser/public/recipe-images/374389_319334758125900_100001481363302_872650_1682347917_n.jpg_7.jpg?VersionId=aTJyA_u17BMf78cR1_bTjo1I.rc6FwZQ&itok=8VfZojcI"
    },
    {
      "URL": "https://www.smulweb.nl/recepten/1135566/Babi-ketjap",
      "ingredients": "['* 500 gram mager varkensvlees (fricandeau of ', 'hamlappen', ') * 5 eetlepels ', 'ketjap manis', ' * halve ', 'prei', ' in smalle repen gesneden * 1 zeer fijn gesnipperde ', 'ui', ' * 3 teentjes geperste ', 'knoflook', ' * 1 eetlepel ', 'djahe', ' * 1 theelepel ketoembar * 1 theelepel djinten * 1 theelepel zwarte ', 'peper', ' * 2 eetlepels ', 'azijn', ' * 6 eetlepels slaolie * 2 theelepels ', 'sambal', ' * 1 flinke mespunt vetsin * 1-2 eetlepels witte basterdsuiker * 2 dl. water * zout * ', 'bindmiddel', '.']",
      "title": "Babi Ketjap",
      "description": "Dit recept gebruik ik al jaren. Dit is echt zo lekker en iedereen kan het maken. Kan niet mislukken.",
      "steps": "Verwarm de rest van de olie. Schep het vlees uit de marinade. Laat die uitlekken en bak het op hoog vuur mooi van kleur. Voeg daarbij af en toe wat van de marinade om te voorkomen dat de snippers prei en ui te donker worden.Roer de sambal, vetsin en suiker door het vlees. Schenk de rest van de marinade en het water erbij en laat het vlees nog ongeveer 20 minuten sudderen. Naar smaak eventueel nog extra sambal, suiker en zout toevoegen. Het geheel een beetje binden zodat de saus wat aandikt.",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/styles/recipe_teaser/public/recipe-images/babi_ketjap_600.jpg_10.jpg?VersionId=kDntv4FYhCC_Ozs5t2IMwz5tC8LpAXsZ&itok=26FX0c9j"
    },
    {
      "URL": "https://www.smulweb.nl/recepten/1097907/Ovenschotel-a-la-louise",
      "ingredients": "['1 \u00bd kilo ', 'aardappelen', ' - ongeschild gewicht- (of als je geen tijd hebt puree uit een pakje maar vers is echt veel smakelijker)', '1 pond gehakt (halfom of runder en ongekruid).br ']",
      "title": "Ovenschotel a la louise",
      "description": "Dit recept is al jaren oud en heb ik ooit gekregen van een nicht van mij.In de \"loop der jaren\" heb ik het aangepast naar eigen smaak en het is nu gewoon (na alle veranderingen) mijn \"eigen\" recept geworden.. Het is h\u00e9\u00e9l erg lekker, ik hoor graag reacties!Nieuwe fotos staan nu bij dit recept.Gisteren 8 oktober 2010 weer gemaakt, (weer iets aangepast) en.. het was weer superlekker!",
      "steps": "VoorbereidingOvenschotel invetten met wat boter of olie./Verwarm de oven voor op 175- 180\u00b0C.Zet de aardappels op en kook ze gaar.Ondertussen doe je het gehakt in een grote Anti-aanbakpan (of in een wok).Zet het op een laag vuur zodat het eigen vet loslaat (dus geen boter of olie in de pan doen).Breek het gehakt regelmatig met een houten lepel.Als er voldoende vet is uitgelopen zet het vuur dan hoog en laat het bruin worden.Haal het gehakt uit de pan en doe het in een schaal.Doe wat boter of olie in de pan en bak de uien (met eventueel de bruine suiker) tot ze glazig zijn.Bak op het laatst de knoflook even mee.Voeg dan de gesneden prei en als je hebt verse selderij toe, als dat goed vermengd is voeg je de champignons en de spitskool toe, even goed doorbakken.Doe het gehakt, peper, zout, gedroogde kruiden, kerrie, ketchup en ketjap erbij.Proef of er voldoende kruiden inzitten, voeg eventueel nog kruiden naar smaak toe.Maak aardappelpuree en voeg eventueel nog een scheutje melk (of room) toe.Roer alles goed door elkaar en doe het in de ingevette ovenschaal.Als je wat puree apart hebt gehouden strijk je het uit over de schaal.Strooi er de geraspte kaas over.Bak in de oven voor ongeveer 20- 25 minuten",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/styles/recipe_teaser/public/recipe-images/foto1.jpg_6.jpg?VersionId=Q6uu0mEtmy6h7.SpLjmvYny5ldImy0Od&itok=LZNHiO5D"
    },
    {
      "URL": "https://www.smulweb.nl/recepten/1141872/Heerlijke-pastasalade",
      "ingredients": "['* 4 ons ', 'pasta', ' (bijvoorbeeld wokkels of ', 'penne', ') * 3 ons ', 'kipfilet', ' * kipkruiden * 6 pruimtomaten * bakje ', 'pijnboompitten', ', * half potje ', 'groene pesto', ' * stuk parmezaanse ', 'kaas', ' * zak gesneden ', 'ijsbergsla', ' of een halve krop', '']",
      "title": "Heerlijke pastasalade",
      "description": "Echt lekkere pastasalade met onder andere kip, pesto, tomaat en parmezaanse kaas, heerlijk als maaltijdsalade of bij een zomers buffet, recept gekregen van een vriendin",
      "steps": "* Bak de kipfilets met wat kipkruiden, laat hem afkoelen en snijdt aan stukjes. * kook de pasta in water met wat zout, giet af en spoel koud * Meng de pasta met de kipfilet, tomaatblokjes en een flinke klodder pesto. voeg vlak voor het serveren de parmezaanse kaassnippers, geroosterde pijnboompitten en ijsbergsla toe zodat dit knapperig en vers blijft",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/recipe-images/63274a206997e-pastasalade_met_pesto.jpg.jpg?VersionId=EAV2Nq6IeRNrEpmd6MJW_Z6nghngGIl2&itok=xLZoSJ0c"
    },
    {
      "URL": "https://www.smulweb.nl/recepten/1310114/Stifado-voor-de-slowcooker-of-oven",
      "ingredients": "[' Eerst even dit; Komt het vlees van een koude buitenlucht of uit de koelkast? Laat het `even wennen` want als het ijskoud de pan in gaat dan is het gedaan met het malse vlees! \u00b1 800 g runderlappen.(wat doorregen runderlappen vindt ik lekker)', '', '4-5 el ', 'olijfolie', '.', '', '5 teentjes ', 'knoflook', ' (of naar smaak)uit de knijper of gesneden 1 blik tomatenblokjes. 250 g sjalotjes. 50 ml ', 'rode wijn', '. 25 ml rode wijnazijn  \u00bd -1 afgestreken tl ', 'kaneel', '.\u00bd-1 afgestreken tl geraspte ', 'nootmuskaat', '2 laurierblaadjes. 1 mespuntje kruidnagelpoeder. \u00bd tl gemalen komijn vers gemalen zwarte ', 'peper', ' en zout naar smaak1 klein blikje tomatenpuree.  50 g ', 'boter', '.(of minder naar eigen smaak) \u00b1 10 gedroogde tomaten op ', 'olie', ', in stukjes gesnedenScheutje Worcestershire sauce. plusminus 300 ml water.(hangt van je pan af, het vlees moet net onder staan).', '', '\u00b1 1 el ', 'bloem', ' om het vlees mee te bestrooien plus plastic zak (om vlees en bloem in te doen)', '', 'Soms voeg ik een snufje ', 'chili', ' of Cayenne toe, hoort absoluut niet maar wij vinden het lekker.']",
      "title": "Stifado voor de slowcooker of oven",
      "description": "Stifado is een heerlijk Grieks gerecht. Ik maak het in de slowcooker maar toen ik die nog niet had maakte ik het in de oven. Er bestaan veel recepten van Stifado maar dit is heel lekker! Toen ik het eens wilde proberen vond ik zoveel verschillende recepten op internet en in Griekse kookboeken dat ik eerst ging proberen wat nu wel en niet lekker was. Van verschillende recepten ingredi\u00ebnten gebruikt en/of weggelaten en zo heb ik het recept iedere keer wat veranderd naar mijn eigen smaak en misschien zijn er een paar ingredi\u00ebnten bij dit er niet in horen maar dit is het geworden en zo vinden wij het heerlijk! Toen het \"oude smulweb\" er nog was kreeg ik bij dit recept een groot compliment van de kok van een Grieks restaurant in ons land. Helaas is dit bericht verloren gegaan maar ik was er heel blij mee. Misschien wil je het wat pittiger of meer z/p wilt toevoegen? Even proeven. Soms voeg ik een snufje chili of cayenne toe, hoort absoluut niet maar wij vinden het lekker.",
      "steps": "Doe bloem in de plastic zak, het vlees erbij en even goed schudden, zo wordt het dun bedekt met wat bloem.Doe de olijfolie in de koekenpan of juspan en bak het vlees op matig vuur rondom iets aan.Voeg dan al roerende de kruiden en de knoflook toe en meng alles goed door elkaar.Voeg peper en zout naar smaak toe. Giet de azijn en rode wijn toe en laat het ongeveer 2 -3 minuten zachtjes pruttelen.Voeg de tomaten uit blik, de gedroogde tomaten ,tomatenpuree en de Worcestershire sauce toe.Doe alles over in de slowcooker OF de ovenvaste schaal. Voeg dan het water toe en let erop dat het vlees onderstaat.Leg de sjalotjes boven op het vlees en daarop de boter. Deksel op de slowcooker (of braadpan).Voor de slowcooker; zet de slowcooker 1 uur op high en 6-7 uur op low (het hangt van je slowcooker af, bij mij is deze timing perfect bij een ander misschien korter).Voor de oven is de tijd ongeveer 2-3 uur. (kijk/proef tussendoor)",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/recipe-images/63274adf962e9-Stifado_f11.jpg.jpg?VersionId=z9B3IPKb6K6aVS626qL0hciciUfzJAE6&itok=xdvaSE86"
    },
    {
      "URL": "https://www.smulweb.nl/recepten/1383253/De-allerlekkerste-babi-pangang",
      "ingredients": "['1 kilo ', 'hamlappen', ',', '', '2 kleine blikjes ', 'tomatenpuree', ',', '', '2 eetlepels ', 'ketchup', ',', '', '3 eetlepels ketjap ,', '', '2 eetlepels ketjap ,', '', '2a3 theelepels ', 'sambal', ',', '', '1/2 liter water,', '', '1 pot ', 'atjar', ' tjampoer,', '', '1 kopje ', 'suiker', ',', '', 'maizena', ',', '', '3 teentjes ', 'knoflook', ',', '', '1 knijpje chilipasta , of een eetlepel sambal,', '', '1 theelepel gemberpoeder,', '', 'zout']",
      "title": "De allerlekkerste Babi pangang",
      "description": "Deze babi pangang is in een handomdraai gemaakt met de kruiden die vrijwel altijd in je keuken te vinden zijn.",
      "steps": "Braad het vlees kort voor op hoog vuur, doe dan de tomatenpuree, ketchup, de rest van de ketjap, sambal, water, potje atjar tjampoer , en de suiker bij het vlees. Heerlijk laten sudderen tot het vlees gaar is. Op het laatst aangemaakte maizena toevoegen om de saus dikker te maken, zout naar smaak toevoegen. Super makkelijk en altijd een succes!!",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/recipe-images/63274cddef2c7-340064-b10e633b7e0232ddf9a266ac75a96a2f.jpg.jpg?VersionId=ZQpRZEjfjFtljzz2XVw5NY8QFBOTS.HW&itok=odHWzyJ5"
    },
    {
      "URL": "https://www.smulweb.nl/recepten/1147314/Grieks-rundvlees-uit-de-oven",
      "ingredients": "['600 g ', 'riblappen', ' of ', 'runderlappen', ', in grove stukken', \"br 2 eetlepels rode-wijnazijn br br 3 eetlepels olijfolie br br 1 eetlepel gedroogde oregano br br 2 theelepels chilipoeder br br 1 eetlepel tomatenpuree br br 125 ml vleesbouillon (van 1/4 tablet) br br 4 tomaten, in partjesbr br 2 gele paprika's, in grove stukkenbr br 200 g Griekse feta (kaas)\"]",
      "title": "Grieks rundvlees uit de oven",
      "description": "Jammie jammie...dit is z\u00f3oooo lekker...(let wel op de lange bereidingstijd in de oven.. hoe langer de kruiden en specerijen in het vlees kunnen trekken, hoe lekkerder het uiteindelijke resultaat...!)",
      "steps": "In Ovenschaal vlees mengen met azijn, olie, oregano en chilipoeder. Smaken 15 min. laten intrekken. Tomatenpuree, zout en peper door vlees scheppen. Bouillon erdoor roeren. Ovenschaal met deksel erop in koude oven schuiven. Oven inschakelen op 175 \u00b0C. Vlees in minstens 2 uur zachtjes gaarstoven. Vlees af en toe omscheppen en na 1 uur tomaten en paprika erdoor mengen. Schaal uit oven nemen en feta erboven verkruimelen. Serveren met rijst en een ijsbergsalade met olijven.",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/recipe-images/63274a2be9102-1339417160.jpg.jpg?VersionId=LW8fFt40hag_TAZOjtvzO7Q_wfYZjdEJ&itok=0QVfyq3Q"
    },
    {
      "URL": "https://www.smulweb.nl/recepten/1027465/Roti-met-kip-aardappelen-kousenband-en-ei",
      "ingredients": "['Voor de ', 'roti', ': 500 gr. ', 'zelfrijzend bakmeel', ', 300 ml. water, 150 gr. gele spliterwten, 1 eetl. gemalen komijnzaad, 2 tn. uitgeknepen ', 'knoflook', ', 100 ml. ', 'olie', ', zout en ', 'peper', '.', '', '\\nvoor de rotimix: 350 ml (= ong. 2 kopjes) water, 2 tn. uitgeknepen knoflook (te vervangen door een theel. uienpoeder), een fijngesneden kleine ', 'ui', \", een half rood pepertje of 1 gedroogd pepertje, 2 eetl. olie, 2 eetl. kerrie (dit luistert nauw, het moet speciale Surinaamse zijn, ik gebruik \\\\'Nandan Massala\\\\'), 1 theel. vetsin, 2 bouillonblokjes, 1 klein blikje \", 'tomatenpuree', ', 6 middelgrote geschilde ', 'aardappelen', ', 1 dubbele ', 'kipfilet', ' in blokjes, 3 hardgekookte eieren, 250 gr. kousenband of dunne spercieboontjes in kleine stukjes gesneden of geknipt.']",
      "title": "Roti met kip, aardappelen, kousenband en ei",
      "description": "het zoveelste roti-recept op het smulweb, maar deze is zo lekker!",
      "steps": "De roti: Verhit een grote koekenpan zonder olie, leg de roti in de pan en kwast ondertussen de bovenkant in met olie. Draai de roti dan direct om en smeer de andere kant in. Bak de roti aan beide zijden goudgeel tot ze even bol gaat staan, net als een pannekoek. In totaal is de baktijd per roti ongeveer 5 minuten.De mix: Snij of knip het pepertje fijn en was hierna goed je handen. Fruit ui, peper en evt. knoflook in 2 eetl. olie. Voeg de tomatenpuree en het kerriepoeder toe, doe er de vetsin en het water bij, verkruimel de bouillonblokjes hierover. Laat dit even zachtjes koken en doe de aardappelen, kip- en groentenstukjes erbij. Warm tot slot de hele of halve eieren mee in de pan.",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/recipe-images/632748f9f3694-428888_10151010104532766_1161479366_n.jpg.jpg?VersionId=6OwpZ8fDAWpxWnKpUVUnbqJ0BgE5MCDr&itok=C5xLNlJt"
    },
    {
      "URL": "https://www.smulweb.nl/recepten/1100544/Gesmolten-kaaspasta-met-gegrilde-kip-groenten",
      "ingredients": "[<br>2 kipfilets<br>150 gram <a href=\"https://www.smulweb.nl/recepten/paddenstoelen/champignons\">champignons</a><br>1 rode <a href=\"https://www.smulweb.nl/recepten/paprika\">paprika</a><br>1 el fijngehakte <a href=\"https://www.smulweb.nl/recepten/basilicum\">basilicum</a><br>1 fijngesneden rode <a href=\"https://www.smulweb.nl/recepten/peper\">peper</a><br>1 tl <a href=\"https://www.smulweb.nl/recepten/suiker\">suiker</a><br>1 el limoensap<br/>150 gram <a href=\"https://www.smulweb.nl/pasta\">pasta</a> (<a href=\"https://www.smulweb.nl/recepten/penne\">penne</a>, fusilli)<br/>1 dl <a href=\"https://www.smulweb.nl/recepten/room/kookroom\">kookroom</a><br/>75 gram pittige, <a href=\"https://www.smulweb.nl/recepten/geraspte+kaas\">geraspte kaas</a><br/><a href=\"https://www.smulweb.nl/recepten/olie/olijfolie\">olijfolie</a><br/></br></br></br></br></br></br></br>]",
      "title": "Gesmolten Kaaspasta met Gegrilde Kip & Groenten",
      "description": "HEEEEEEEEEEEERLIJK recept van Ramon Beuk!!Van de week gezien op teevee, vanavond gemaakt en het komt beslist vaker op tafel.Penne in een sausje van gesmolten kaas met gegrilde kipfilet en gegrilde groenten. Het was superlekker!!! Thank you Ramon.",
      "steps": "Snijd de kip in dunne plakken en doe ze in een mengkomVoeg wat olijfolie toe aan de kipfilet en bestrooi flink met versgemalen peper (eventueel wat paprikapoeder)Meng de olie + kruiden goed door de kipfiletKook de pasta zoals op de verpakking staat aangegevenLaat de grillpan heet worden en grill de kipfilet zonder extra olie toe te voegen tot ze mooi gaar zijnDoe de kipfilet daarna in een grote schaal en dek deze afSnijd de champignons en rode paprika in grove stukken en doe ze in de mengkomMeng er wederom olie en flink wat versgemalen peper (en eventueel wat paprikapoeder) doorheenGrill de groenten ook in de grillpan tot ze mooi gaar zijn en voeg ze dan toe aan de kipfiletVoeg de verse basilicum, rode peper, suiker, limoensap, peper en zout toe aan het kip/groentemengsel en zet dan de deksel weer op de schaalDoe de melk en kaas in een pan en laat dit smelten (blijven roeren)Roer de pasta door de kaassausSchep de kaaspasta op een bord en leg het groente/kipmengsel er bovenopVersier met wat dungesneden sliertjes verse basilicum",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/styles/recipe_teaser/public/recipe-images/1351090445.jpg_3.jpg?VersionId=gSWXr9KUMQWHJqRwvqfFHytQRafC8slG&itok=MwuLOjib"
    },
    {
      "URL": "https://www.smulweb.nl/recepten/1352305/Visschotel-a-la-ine",
      "ingredients": "['4 pangasiusfilets (diepvries)', '', '1 bakje roze ', 'garnalen', '', '2 winterpenen', '', '3 grote ', 'uien', '', '5 grote ', 'tomaten', '', '3 bosuitjes', '', '3/4 bakje Philadelphia ', 'bieslook', ' light', '', '2 tenen ', 'knoflook', '', '3 eetlepels ', 'geraspte kaas', '', '1 visbouillontablet', '', 'peper', ', zout', '', '2 a 3 eetlepels ', 'olijfolie']",
      "title": "Visschotel a la Ine.",
      "description": "Heerlijk en slank !",
      "steps": "Verwarm de oven voor op 220 gr.Snijd de uien in grove stukken, schaaf de winterwortel met `n dunschiller aan linten, pers de knoflook, snijd de tomaten in grove stukken en ook de bosuitjes.Verhit de helft van de olie en fruit daarin op matig vuur de ui met de knoflook en de wortel.Verkruimel er de visbouillontablet over en laat even smoren.Schep uit de pan in een Ovenschaal.Doe de rest van de olie in de pan en roerbak de tomaat en de bosui met versgemalen zout en peper 2 min. op hoog vuur.Leg de (bevroren) visfilets op het wortel/ui-mengsel.Bestrooi met peper en zout, en besmeer ze met de Philadelphia. Verdeel er de garnalen over, en daar bovenop het tomaat/bosui-mengsel.Bestrooi met de geraspte kaas en zet de schaal  40 min. in de oven.",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/recipe-images/63274b7472974-viss.jpg.jpg?VersionId=A_EPwcsRVY53CBRZWk179QZh2.QmbLfi&itok=Wm0GDPFZ"
    },
    {
      "URL": "https://www.smulweb.nl/recepten/1142076/Franse-klassieke-boeuf-bourguignon",
      "ingredients": "['1 kilo magere ', 'runderlappen', ', in grove stukken  300 gr ', 'wortelen', '  3 teentjes ', 'knoflook', '  4 rode ', 'uien', '  250 gr kastanje ', 'champignons', ' in plakjes  3 el ', 'olijfolie', '  halve pot ', 'vleesfond', '  2 el ', 'bloem', '  100 gr spekreepjes  500 ml ', 'rode wijn', ' (bourgogne)']",
      "title": "Franse klassieke Boeuf Bourguignon",
      "description": "Belangrijk voor dit SUPER gerecht echt een goede wijn te nemen. Is echt een TOPPERTJE",
      "steps": "In ovenvaste braadpan olie verhitten en vlees rondom bruinbakken. Ui, knoflook en wortel 2 minuten meebakken. Tijm, bloem en zout en peper er over strooien. Langs rand van de pan fond en wijn erbij schenken. Braadpan afgedekt met deksel in midden van oven schuiven en vlees in 2 uur zachtjes gaarstoven. Af en toe omscheppen en eventueel nog scheutje wijn of water toevoegen. In koekenpan spekreepjes zachtjes uitbakken. Champignons toevoegen en 3 minuten op hoog vuur meebakken. Pan uit oven nemen en champignonmengsel door vlees scheppen. Pan nog 15 minuten  in oven laten staan. Lekker met aardappels en broccoli.",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/recipe-images/63274a278cf63-webredactie.jpg.jpg?VersionId=xzTU8k3HriJiCrb8pzfB_zg0nlU0mhEO&itok=0R47ctfb"
    },
    {
      "URL": "https://www.smulweb.nl/recepten/1313020/Ouderwetse-hachee",
      "ingredients": "['500 gr.hacheevlees of ', 'runderlappen', ' (op kamertemperatuur)', '', '500 gr.', 'uien', '', '2 th.l.rietsuiker', '', '2 eetl.', 'bloem', '', '5 dl.', 'runderbouillon', ' van tablet', '', '1 fl.leffe bruin of bruin ', 'bier', '', '2 blaadjes laurier', '', '2 kruidnagels', '', '100 gr.margarine', '', 'flinke scheut ', 'olie', '(om te ', 'bakken', ')', '', 'Peper en zout', '', '2 sneetjes ', 'peperkoek', ' in blokjes', '']",
      "title": "Ouderwetse hachee",
      "description": "Een heerlijke ouderwetse hachee die het lekkerste is om deze 1 dag tevoren te maken.",
      "steps": "Margarine in de pan smelten en tegen de tijd dat de belletjes wegtrekken een flinke scheut olie erbij doen en goed heet laten worden.Ondertussen het vlees bestrooien met zout en peper.Vlees in de pan doen en ca. 5 min.goed doorbakken.Uien erbij doen met de rietsuiker en nog eens ca.3 min.doorbakken.Bloem erover strooien en goed doorroeren.De bouillon en het flesje bier even doorwarmen en voorzichtig bij het vlees gieten.De peperkoek erbij doenDe kruidnagel in het laurierblaadje steken en erbij doen.Weer even goed doorwarmen en op een sudderplaatje zolang mogelijk laten garen.",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/recipe-images/638bdce6bd205-ouderwetse_hachee.JPG.jpg?VersionId=NAZUwKHP0.2otVudlutEez3HGRp.0xdO&itok=kz7eqx_u"
    },
    {
      "URL": "https://www.smulweb.nl/recepten/1402026/Big-mac",
      "ingredients": "['Voor 4-5 burgers', '', '', '-400g 100% rundvlees', '', '-', 'hamburger', ' ', 'broodjes', ' met sesam (te krijgen bij oa AH, liever geen `verse` sesam ', 'bolletjes', ')', '', '-', 'mayonaise', '', '-', 'ketchup', '', '-mosterd', '', '-pot zoete ', 'piccalilly', ' ', '', '-pot ', 'augurken', '', '-ui', '', '-', 'ijsbergsla', '', '-cheddar / smeltkaas plakjes (euroshopper)', '', '-witte ', 'azijn', ' of natuurazijn', '', '-zout, ', 'peper', ', suiker']",
      "title": "Big mac",
      "description": "Thuis je Big mac maken. Bijna niet van echt te onderscheiden.",
      "steps": "Snipper een halve ui en 3 augurken liefst in een Blender, houd de ingredienten apart.De saus is belangrijk en luistert heel nauw proef vaak.Meng 2 eetlepels mayo met 1/2 eetlepel ketchup, 1 theelepel mosterd en ong 1 eetlepel piccalilly. Voeg 1 eetlepel (afgestreken) ui en augurk (gesnipperd) toe. Voeg een snufje zout toe en een 1,5 theelepel suiker. Voeg tenslotte een paar druppels azijn toe. Meng alles goed en proef regelmatig. Te zuur? meer suiker en piccalilly, voorzichtig met ketchup. Te zoet? iets meer azijn en/of zout, voorzichtig met mayo en mosterd. Probeer te voorkomen dat de saus naar mayo smaakt. Ik voeg meestal ook nog een klein beetje belgische mayo toe maar is niet noodzakelijk. De piccalilly smaakt als het goed is al enigszins naar de echte saus.Doe de saus in de koelkast en laat rusten.Snijd de hamburger broodjes zodat je ook een middendeel overhoud. Je kunt ook een onderkant van een 2e broodje gebruiken, maar dan heb je iets teveel brood `in` je burger en houdt een bovenkant over.Snijd de sla in korte reepjes.Snipper de rest van de ui (ditmaal iets minder fijn).Snijd een paar plakjes augurk.Haal het vlees uit de vriezer. Bak de burgers in voldoende olie aan beide kanten op hoog vuur gaar. Omdat ze zo dun zijn duurt dit hooguit 3 minuten. Bestrooi met een heel klein beetje zout en (fijne)peper. Dep de burgers droog op wat keukenpapier (gebruik geen vette burgers)Grill alle lagen van de broodjes aan 1 kant. \u00e9\u00e9n kant moet knapperig zijn en de andere kant nog zacht.Smeer een dun laagje saus (op kamertemperatuur) op het bodem broodje. Voeg een beetje gesnipperde ui toe, van beide niet teveel. Strooi wat sla reepjes erop, wederom niet al te veel.Leg daaroverheen een plak cheddar en vervolgens de burger.Dan het midden broodje, dun laagje saus, wat ui en sla reepjes en tweede burger.Op de bovenste burger leg je 2-3 plakjes augurk, top broodje erop en klaar.Als alles lukt smaakt deze imitatie echt bijna hetzelfde als die van de mac. Experimenteer wat met de saus en vooral doe overal niet teveel van op, dus ook niet sla en ui etc.I`m lovin` it.",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/recipe-images/63c16c546f3d2-big-mac.jpg.jpg?VersionId=X3unlBMiDe77PWqxucXSigu0fpMyKhMN&itok=UzR94Jlh"
    },
    {
      "URL": "https://www.smulweb.nl/recepten/1124980/Bbq-duivelslekkere-griekse-kipspiesen",
      "ingredients": "['1,5 kg ', 'kipfilet', '', 'Voor de marinade:', '', '1,5 - 2 dl ', 'olijfolie', ' of ', 'zonnebloemolie', '', '5 knoflookteentjes, geperst', '', '2 el ', 'oregano', '', '1 tl ', 'dille', '', '2 tl ', 'citroensap', '', '1 tl ', 'paprikapoeder', '', '1 rood pepertje, zeer fijngehakt (incl. zaadjes)', '', '1 ', 'rode ui', ', zeer fijgehakt']",
      "title": "BBQ - Duivelslekkere Griekse Kipspiesen",
      "description": "Hou je van BBQ-en en hou je van de Griekse Keuken???? Dan moet je deze spiesen echt eens gaan proberen. De knoflook en oregano die in de marinade zitten geven je het gevoel alsof je op een warm Grieks eiland in de Middellandse Zee zit.",
      "steps": "Alle ingredienten voor de marinade goed mengenDe kipfilet in lange repen knippen (ik gebruik altijd een vleesschaar, want dat vind ik veel sneller gaan dan snijden)De repen kipfilet zizaggend op de sateprikkers doen (op deze manier voorkom je dat er rauwe kipfilet tussen de stukjes in zit zonder dat deze extra lang hoeft te grillen)Als alle kipfilet op de stokjes zit kunnen deze lekker gemarineerd wordenZet de schaal in de koelkast en laat het zeker 8 uur marineren (dit kan je dus heel goed een avond ervoor doen)Af en toe de stokjes omkeren zodat alle kipfilet goed gemarineerd wordtOp de BBQ grillen en klaar zijn die overheerlijke spiesen",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/recipe-images/632749d0ee187-webredactie.jpg.jpg?VersionId=LujLHtzZG1RikN2a9qxvTbcdwtYbMmrP&itok=sMYlzQbx"
    },
    {
      "URL": "https://www.smulweb.nl/recepten/1367623/Gevulde-courgette",
      "ingredients": "['200gr zilvervliesrijst', '', '\\n200gr ', 'rundergehakt', '', '\\n4 courgettes', '', '\\n3 ', 'tomaten', '', '\\n3 ', 'uien', '', '\\n1 theelepel ', 'paprikapoeder', '', '\\n1 theelepel ', 'kaneel', '', '\\n2 teentjes ', 'knoflook', '', '\\nfijn gehakte verse ', 'peterselie', '', '\\n100gr 30+ ', 'kaas', ' (geraspt)', '', '\\n1el ', 'olijfolie', '', '\\n', 'peper', ' en zout naar smaak']",
      "title": "Gevulde courgette",
      "description": "Gevulde courgette - sonja bakker recept",
      "steps": "Was de courgettes en hol ze voorzichtig uit. strooi er zout in.Meng het courgette vlees met het gehakt mengsel en en vul hiermee de uitgeholde courgettes. Bestrooi de courgette daarna met 30+ kaas en de fijngehakte peterselie. Zet de courgettes vervolgens in de oven en laat ze in ongeveer 25 minuten op 180 graden gaar worden.",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/recipe-images/63274c3226c60-574814_10151016131222766_1158074311_n.jpg.jpg?VersionId=.ajA2hGIIlU2yuZc34i05mNJQqvb8fdB&itok=N8V2widr"
    },
    {
      "URL": "https://www.smulweb.nl/recepten/1140206/Chinese-tomatensoep",
      "ingredients": "['# 1 liter water ', '', '', '\\n# 1 liter ', 'tomatensap', ' ', '', '', '\\n# 2 kipfilets ', '', '', '\\n# 2 kippenbouillonblokjes ', '', '', '\\n# 1 ', 'ui', ' ', '', '', '\\n# 2 tenen ', 'knoflook', ' ', '', '', '\\n# blikje ', 'tomatenpuree', ' ', '', '', '\\n# 6 el ', 'suiker', ' ', '', '', '\\n# 4 el ketjap (manis) ', '', '', '\\n# 2 el ', 'azijn', ' ', '', '', '\\n# 1 borrellepeltje ', 'sambal', ' ', '', '', '\\n# 1 borrellepeltje ', 'djahe', ' (gemberpoeder) ', '', '', '\\n# 1 borrellepeltje sereh (', 'citroengras', ') ', '', '', '\\n# 2 el ma?zena ', '', '', '\\n# Handje vol ', 'mihoen', ' ', '']",
      "title": "chinese tomatensoep",
      "description": "een heerlijke soep die de chinese tomatensoep van de chinees evenaart.",
      "steps": "# roerbak de ui totdat deze glazig is. Voeg het vlees toe en bak dit even aan.# Voeg de knolfook en de tomatenpuree toe.# Blus af met een liter water. Voeg de bouillonblokjes toe. Laat een uurtje zachtjes pruttelen.# Haal het vlees uit de bouillon# Voeg 1 liter tomatensap toe en breng aan de kook# Zet het vlees gesneden in een apart schaaltje# Maak in een ander schaaltje een prutje van: suiker, ketjap, azijn, sambal, dajahe en sereh# Roer dit prutje en voeg dit aan de tomatenbouillon toe# Roer de maizena door een kopje koud water, roer dit tot een gladde massa en voeg dit aan de soep toe (binden)# Voeg de mihoen toe# Laat alles 20 minuten zachtjes doorkoken# Vlees toevoegen# 2e dag nog lekkerder",
      "imgURL": "https://d1mlbwr23caxox.cloudfront.net/public/sites/default/files/styles/large/public/recipe-images/62518c2aaba20-1334578926.jpg.jpg?VersionId=ndQ7Oi4K3Lfr9Wo.ZplsXKYfNx2Cbz_j&itok=Tb_SUxYw"
    }
  ]